# Generated by Django 5.2.17 on 2026-10-05 23:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor objetivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor acumulado')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['active', 'deadline', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='is_subscription',
            field=models.BooleanField(default=False, verbose_name='É assinatura?'),
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pago?'),
        ),
        migrations.AddField(
            model_name='fixedexpense',
            name='recurrence',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Recorrência'),
        ),
    ]
