# Generated by Django 5.2.17 on 2026-10-06 00:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_goal_fixedexpense_is_subscription_fixedexpense_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardexpense',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Parcela paga?'),
        ),
        migrations.AddField(
            model_name='creditcardexpense',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento'),
        ),
        migrations.AddField(
            model_name='creditcardexpense',
            name='reimbursed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor reembolsado'),
        ),
        migrations.AddField(
            model_name='creditcardexpense',
            name='reimbursed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data do reembolso'),
        ),
    ]
