# Generated by Django 5.2.17 on 2026-10-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_creditcardexpense_paid_creditcardexpense_paid_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_gross', models.DecimalField(decimal_places=2, default=3000, max_digits=12, verbose_name='Salário bruto')),
                ('salary_net', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salário líquido')),
                ('previous_net_salary', models.DecimalField(decimal_places=2, default=2299, max_digits=12, verbose_name='Salário líquido anterior')),
                ('vr_monthly_credit', models.DecimalField(decimal_places=2, default=500, max_digits=12, verbose_name='Crédito mensal de VR')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Perfil financeiro',
                'verbose_name_plural': 'Perfil financeiro',
            },
        ),
    ]
