# Generated by Django 5.2.17 on 2026-10-06 02:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financialprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_month', models.DateField(unique=True, verbose_name='Mês da fatura')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Pago em')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago')], default='PENDING', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['-invoice_month'],
            },
        ),
        migrations.CreateModel(
            name='SalarySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True, verbose_name='Mês')),
                ('salary_gross', models.DecimalField(decimal_places=2, default=3000, max_digits=12, verbose_name='Salário bruto')),
                ('salary_net', models.DecimalField(decimal_places=2, default=2751.2, max_digits=12, verbose_name='Salário líquido')),
                ('vr_monthly_credit', models.DecimalField(decimal_places=2, default=500, max_digits=12, verbose_name='VR mensal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.AddField(
            model_name='creditcardexpense',
            name='import_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Identificador da importação'),
        ),
        migrations.AddField(
            model_name='creditcardexpense',
            name='invoice_month',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Mês da fatura'),
        ),
        migrations.AddField(
            model_name='creditcardexpense',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da compra'),
        ),
        migrations.AlterField(
            model_name='financialprofile',
            name='salary_net',
            field=models.DecimalField(decimal_places=2, default=2751.2, max_digits=12, verbose_name='Salário líquido'),
        ),
    ]
