# Generated by Django 5.2.17 on 2026-10-06 02:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_creditcardbill_salarysnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardexpense',
            name='vr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor pago com VR'),
        ),
    ]
