# Generated by Django 5.2.17 on 2026-10-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_creditcardexpense_vr_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='investment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='finance.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='investment',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CREDIT_CARD', 'Cartão de crédito'), ('DEBIT', 'Débito'), ('CASH', 'Dinheiro'), ('BOLETO', 'Boleto'), ('VR', 'Vale Refeição')], default='PIX', max_length=20, verbose_name='Conta utilizada'),
        ),
        migrations.AddField(
            model_name='investment',
            name='recurrence',
            field=models.CharField(choices=[('ONE_TIME', 'Único'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='ONE_TIME', max_length=10, verbose_name='Periodicidade'),
        ),
        migrations.AddField(
            model_name='salarysnapshot',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo inicial'),
        ),
    ]
