# Generated by Django 5.2.17 on 2026-10-06 23:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_monthly_balance_and_investment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vr_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor pago com VR'),
        ),
        migrations.AddField(
            model_name='vrmovement',
            name='card_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vr_movements', to='finance.creditcardexpense', verbose_name='Compra no cartão'),
        ),
        migrations.AlterField(
            model_name='vrmovement',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vr_movements', to='finance.transaction', verbose_name='Lançamento'),
        ),
    ]
