# Generated by Django 5.2.17 on 2026-10-07 00:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_link_legacy_card_vr_movements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da parcela'),
        ),
    ]
